[add] comoto_cli check dialyzer

diff --git a/comoto_cli/command/check b/comoto_cli/command/check
--- a/comoto_cli/command/check
+++ b/comoto_cli/command/check
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+# TODO add a check for e.g. unused elixir vars. Or really, anything that causes a compilation error with --warnings-as-errors
 . $COMOTO_CLI_ROOT/lib/print
 
 _comoto_cli_command_summary='Quality-control your code locally, before it gets to Circle CI'
@@ -26,15 +27,9 @@ Examples
 All checks are run in the local rz container.
 
 EOF
-# TODO add examples to the main comoto_cli help
 }
 
 _credo() {
-  # TODO copy this pattern to the other scripts
-  # TODO can `mix credo` be in single quotes?
-  # TODO I don't think the cd is necessary
-  # TODO add the rz-repl to comoto_cli
-
   comoto_cli bash rz 'mix credo'
 
   credo_exit_code=$?
@@ -42,6 +37,7 @@ _credo() {
   echo
   if [[ ! $credo_exit_code -ne 0 ]]
   then
+    # TODO when Ctrl+C, the exit code is wrong
     print_success 'Credo check succeeded'
   else
     print_fail 'Credo check failed'
@@ -51,16 +47,61 @@ _credo() {
 }
 
 _dialyzer() {
-  echo "TODO: implement the dialyzer check"
-  :
+  # TODO DRY this out?
+  comoto_cli bash rz 'mix dialyzer'
+
+  dialyzer_exit_code=$?
+
+  echo
+  if [[ $dialyzer_exit_code -eq 0 ]]
+  then
+    print_success 'Credo check succeeded'
+  else
+    print_fail 'Credo check failed'
+  fi
+
+  return $dialyzer_exit_code
+}
+
+local commands=''
+_add_a_new_command() {
+  if [[ -z $commands ]] ; then
+    commands="$1"
+  else
+    commands="$commands && $1"
+  fi
 }
 
 _comoto_cli_command_execute() {
+  if [[ $# -eq 0 ]] ; then
+    echo "arg count: $#"
+    comoto_cli check credo dialyzer
+    return $?
+  fi
+
+  for arg
+  do
+    case $arg in
+      credo) _add_a_new_command "comoto_cli bash rz 'mix credo'" ;;
+      dialyzer) _add_a_new_command "comoto_cli bash rz 'mix dialyzer'" ;;
+      *) print_usage_error && return 1 ;;
+    esac
+  done
+  print_and_eval_command -c "$commands"
   # TODO typing 'm check -he' should produce an error, but credo runs anyway
-  # TODO implement the credo and dialyzer args
-  _credo && _dialyzer
 }
 
 _comoto_cli_command_completion() {
-  :
+  local valid_checks=(credo dialyzer)
+  local cur_word="${COMP_WORDS[$COMP_CWORD]}"
+  for i_arg
+  do
+    if [[ $i_arg != $cur_word ]] ; then
+      valid_checks=("${valid_checks[@]/$i_arg}")
+    fi
+  done
+  # TODO DRY this line out? I keep having go find and copy it from other scripts
+  unused_checks="${valid_checks[@]}"
+  # TODO standardize my var names. Elsewhere I use cur_arg
+  COMPREPLY=( $(compgen -W  "$unused_checks" -- "$cur_word") )
 }
