[add] comoto_cli bash --staging

diff --git a/comoto_cli/command/repl b/comoto_cli/command/repl
--- a/comoto_cli/command/repl
+++ b/comoto_cli/command/repl
@@ -27,11 +27,29 @@ EOF
 # TODO add autocomplete
 # TODO error out when given an invalid $1
 _comoto_cli_command_execute() {
-  case $1 in
-    # TODO is this correct or should this be in the "bash" command?
-    ecom) subcommand="ecom-bash" ;;
-    cg|jp|rz) subcommand="$1-iex" ;;
-    *) print_usage_error && exit 1
+  the_env='dev'
+  OPTIND=1
+  while getopts "ds" opt; do
+    case $opt in
+      d)  the_env='dev' ;;
+      s)  the_env='staging' ;;
+      *) echo "$0: error" >&2; exit 1
+    esac
+  done
+  shift $((OPTIND-1))
+
+  case $the_env in
+    dev)
+      case $1 in
+        # TODO is this correct or should this be in the "bash" command?
+        ecom) subcommand="ecom-bash" ;;
+        cg|jp|rz) subcommand="$1-iex" ;;
+        *) print_usage_error && exit 1
+      esac
+      ;;
+    staging)
+      subcommand="kube-iex $($COMOTO_CLI_ROOT/lib/container_name)"
+      ;;
   esac
 
   print_and_eval_command --include-type "$subcommand"
diff --git a/comoto_cli/lib/kube b/comoto_cli/lib/kube
--- a/comoto_cli/lib/kube
+++ b/comoto_cli/lib/kube
@@ -5,6 +5,7 @@
 # view all functions that aren't help functions
 # cat bash_functions.sh | grep ^function | sed 's/function //' | sed 's/(.*//' | grep -v ^_.*help$
 
+. $COMOTO_PROJECT_ROOT/monorepo/zlaverse/support/bash_functions.sh
 
 _comoto_cli_command_summary='Get your gcloud password (for e.g. connecting to staging db)'
 _comoto_cli_command_usage='comoto_cli gcloudlogin'
@@ -74,6 +75,7 @@ _comoto_cli_command_completion() {
   COMPREPLY=( $(compgen -W '-s -b' -- "$cur_word"))
 }
 
+# not used right now
 _comoto_cli_command_execute() {
 
   OPTIND=1
@@ -87,10 +89,41 @@ _comoto_cli_command_execute() {
         # Shell
         _comoto_cli_kube_generatepodlist
         local podname=$(fzf < "$_kubepodlist")
-        print_and_eval_command "kube-bash $podname"
+        print_and_eval_command --include-type "kube-bash $podname"
         return
         ;;
       *) echo "$0: error" >&2; exit 1
     esac
   done
 }
+
+# USAGE
+#   $0 bash --pr PR_NUMBER ecom|cg|jp|rz
+#   $0 bash --current-pr   ecom|cg|jp|rz
+
+# MAIN SCRIPT
+#######################################
+
+# For now, there's only one available command, 'bash'.
+# More will be added later, but for now all we have to do is check for that arg
+if [[ $1 != 'bash' ]] ; then
+  exit 1
+fi
+shift
+
+if [[ $1 == '--pr' ]] ; then
+  shift
+  kube_bash_pr_arg="pr-$2"
+  shift
+fi
+
+case $1 in
+  ecom) container_name='ecom-webapp';;
+  cg) container_name='cycle-gear-redline-webapp';;
+  jp) container_name='jp-cycles-redline-webapp';;
+  rz) container_name='revzilla-redline-webapp';;
+  *) echo "Error! You must pass a valid container name. Got: '$1'" >&2; exit 1
+esac
+shift
+
+print_and_eval_command --include-type "kube-bash $container_name $kube_bash_pr_arg"
