[add] report_on_installation function

diff --git a/lib/headers b/lib/headers
--- a/lib/headers
+++ b/lib/headers
@@ -1,5 +1,7 @@
 #!bin/bash
 
+# TODO rename this file. It's got more than just header stuff
+
 script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
 source $script_dir/../lib/ansi_color
 
@@ -37,6 +39,26 @@ function print_cmd() {
    echo -e "$blue$1$no_color"
 }
 
+report_on_installation() {
+
+  command_name="$1"
+  pretty_print_name=$command_name
+
+  while getopts "p:" opt; do
+    case $opt in
+      p) pretty_print_name=$OPTARG ;;
+      *) echo "$0: error" >&2; exit 1
+    esac
+  done
+  shift $((OPTIND-1))
+
+  if $JJC_CONFIG_DIR/lib/command_exists $command_name
+  then
+    print_success "$pretty_print_name is installed"
+  else
+    print_fail "$pretty_print_name not installed"
+  fi
+}
 
 
 # TODO delete me later
