[update] comoto_cli

diff --git a/moto/command/bounce b/moto/command/bounce
--- a/moto/command/bounce
+++ b/moto/command/bounce
@@ -1,13 +1,29 @@
 #!/bin/bash
 
-# TODO should this migrate as well?
+# USAGE: comoto_cli bounce <container-abbreviation>
 
-# TODO Where is this dir variable defined? I think it can be replaced with $(comoto_cli cd monorepo)
-# TODO make sure all into calls to the cli use `comoto_cli` longform. Add this note to a "contributions" README
-subcommand="comoto_cli cd monorepo && docker-compose down && docker-compose up -d && cd - && comoto_cli logs"
+# TODO rename $COMOTO_CLI_ROOT
+. $COMOTO_CLI_DIR/moto_helpers
 
-source $COMOTO_CLI_DIR/moto_helpers
+if [[ $# -eq 0 ]]
+then
+  # TODO Where is this dir variable defined? I think it can be replaced with $(comoto_cli cd monorepo)
+  # TODO make sure all into calls to the cli use `comoto_cli` longform. Add this note to a "contributions" README
+  subcommand="(comoto_cli cd monorepo && docker-compose down && docker-compose up -d) && comoto_cli logs"
+elif [[ $# -gt 1 ]]
+then
+  echo "error ... must have one or zero args" >&2
+  exit 1
+elif container_name=$($COMOTO_CLI_DIR/lib/container_name $1)
+then
+  # TODO check for bad abbrev
+  # TODO this isn't working
+  subcommand="(comoto_cli cd monorepo docker restart $container_name) && comoto_cli logs $container_name"
+else
+  echo "error ... $1 is a bad arg" >&2
+  exit 1
+fi
 
-print_and_eval_command "$subcommand"
+print_and_eval_command $subcommand
 
 # TODO add the ability to bounce just a single webapp and/or the ability to bounce all three redline apps
