[add] comoto_cli standardized completions

diff --git a/comoto_cli/bashrc b/comoto_cli/bashrc
--- a/comoto_cli/bashrc
+++ b/comoto_cli/bashrc
@@ -10,9 +10,11 @@ export COMOTO_CLI_ROOT="$JJC_CONFIG_DIR/comoto_cli"
 # TODO this shouldn't be hardcoded in here
 # TODO rename COMOTO_PROJECT_ROOT?
 export COMOTO_PROJECTS_DIR="$HOME/projects/comoto"
+export COMOTO_PROJECT_ROOT=$COMOTO_PROJECTS_DIR
 
-# cd to Comoto CLI  dir
-alias cdc="cd $COMOTO_CLI_ROOT"
+
+# TODO this shouldn't live here..
+alias cdc="cd $COMOTO_PROJECT_ROOT"
 
 # Set up github cli command completion
 eval "$(gh completion -s bash)"
@@ -33,25 +35,16 @@ comoto_cli() {
     echo_help
   fi
 
+  local command="$1"
   # Run command if valid or throw error
-  potential_command_path=$COMOTO_CLI_ROOT/command/$1
+  potential_command_path="$COMOTO_CLI_ROOT/command/$command"
   shift
-  if [[ -x $potential_command_path ]] ; then
-    # TODO maybe I shouldn't make a distinction between these two types.
-    # TODO maybe they should all follow the same pattern of sourcing followed by a function call?
-    $potential_command_path $@
-  elif [[ -e $potential_command_path ]]; then
-    unset -f comoto_cli_command_execute
+  if [[ -f $potential_command_path ]] ; then
+    unset -f _comoto_cli_command_execute
     . $potential_command_path
-    if [[ $(type -t comoto_cli_command_execute) == function ]]; then
-      comoto_cli_command_execute $@
-      return $?
-    else
-      echo "Error - expected $potential_command_path to expose a comoto_cli_command_execute function"
-      return 1
-    fi
+    _comoto_cli_command_execute $@
   else
-    echo "No such command" >&2
+    echo "No such command '$command' (TODO: improve error msg)" >&2
     return 1
   fi
 }
@@ -61,20 +54,23 @@ alias m=comoto_cli
 
 export -f comoto_cli
 
-# complete -C $COMOTO_CLI_ROOT/lib/completions comoto_cli
-# complete -C $COMOTO_CLI_ROOT/lib/completions moto
-# complete -C $COMOTO_CLI_ROOT/lib/completions m
-# complete -W "$(ls $COMOTO_CLI_ROOT/command)" moto
+_comoto_cli_completion() {
+  # https://devmanual.gentoo.org/tasks-reference/completion/index.html
 
-_comoto_cli_completions() {
-  echo
-  echo "arg 1: $1"
-  echo "arg 2: $2"
-  echo "arg 3: $3"
-  echo "comp line: $COMP_LINE"
-  COMPREPLY+=("now")
-  COMPREPLY+=("tomorrow")
-  COMPREPLY+=("never")
+  if [[ $COMP_CWORD -eq 1 ]] ; then
+    local cur_word="$2"
+    COMPREPLY=( $(compgen -W "$(ls $COMOTO_CLI_ROOT/command)" -- "$cur_word"))
+    return 0
+  fi
+
+  local cur_command="${COMP_WORDS[1]}"
+  local cur_command_path="$COMOTO_CLI_ROOT/command/$cur_command"
+  if [[ -f $cur_command_path ]] ; then
+    unset _comoto_cli_command_completion
+    . $cur_command_path
+    _comoto_cli_command_completion "${COMP_WORDS[@]:2}"
+  else
+    echo -e "\n'${cur_command}' is an invalid command" >&2
+  fi
 }
-
-complete -F _comoto_cli_completions m
+complete -F _comoto_cli_completion comoto_cli m
diff --git a/comoto_cli/command/bash b/comoto_cli/command/bash
--- a/comoto_cli/command/bash
+++ b/comoto_cli/command/bash
@@ -1,16 +1,31 @@
 #!/bin/bash
 
-# comoto_cli bash
+# USAGE: comoto_cli bash <app_abbreviation>
 
-command='comoto_cli bash'
-. $COMOTO_CLI_ROOT/lib/print $command
+_comoto_cli_command_args="cg jp rz"
 
-# TODO add autocomplete
-# TODO error out when given an invalid $1
+_comoto_cli_command_execute() {
+  command='comoto_cli bash'
+  . $COMOTO_CLI_ROOT/lib/print $command
+  . $COMOTO_PROJECT_ROOT/monorepo/zlaverse/support/bash_functions.sh
 
-case $1 in
-  cg|jp|rz) subcommand="$1-bash" ;;
-  *) echo "TODO this is error msg" >&2 && exit 1
-esac
+  # TODO add autocomplete
+  # TODO error out when given an invalid $1
 
-print_and_eval_command --include-type "$subcommand"
+  case $1 in
+    cg|jp|rz) subcommand="$1-bash" ;;
+    *) echo "TODO this is error msg" >&2 && exit 1
+  esac
+
+  print_and_eval_command --include-type "$subcommand"
+}
+
+_comoto_cli_command_completion() {
+  local cur_arg="${COMP_WORDS[2]}"
+  case $COMP_CWORD in
+    2)
+      COMPREPLY=( $(compgen -W "$_comoto_cli_command_args" -- "$cur_arg") )
+      ;;
+    *) ;;
+  esac
+}
diff --git a/comoto_cli/command/bounce b/comoto_cli/command/bounce
--- a/comoto_cli/command/bounce
+++ b/comoto_cli/command/bounce
@@ -1,29 +1,47 @@
 #!/bin/bash
 
-# USAGE: comoto_cli bounce <container-abbreviation>
+# USAGE: comoto_cli bounce <container_abbreviation>
 
-# TODO rename $COMOTO_CLI_ROOT
-. $COMOTO_CLI_ROOT/lib/print 'comoto_cli bounce'
+# TODO this command isn't working for some reason
+# TODO this command shouldn't take arguments. Instead, it should only take options.
+# TODO weeeellll.... is that true? Or does it just take an arbitrary number, and each arg has to be one of ...
+#   cg
+#   jp
+#   rz
+#   redline
+#   all (default)
+# TODO maybe this should go into the container command
 
-if [[ $# -eq 0 ]]
-then
-  # TODO Where is this dir variable defined? I think it can be replaced with $(comoto_cli cd monorepo)
-  # TODO make sure all into calls to the cli use `comoto_cli` longform. Add this note to a "contributions" README
-  subcommand="(comoto_cli cd monorepo && docker-compose down && docker-compose up -d) && comoto_cli logs"
-elif [[ $# -gt 1 ]]
-then
-  echo "error ... must have one or zero args" >&2
-  exit 1
-elif container_name=$($COMOTO_CLI_ROOT/lib/container_name $1)
-then
-  # TODO check for bad abbrev
-  # TODO this isn't working
-  subcommand="(comoto_cli cd monorepo docker restart $container_name) && comoto_cli logs $container_name"
-else
-  echo "error ... $1 is a bad arg" >&2
-  exit 1
-fi
+_comoto_cli_command_execute() {
+  # TODO rename $COMOTO_CLI_ROOT
+  . $COMOTO_CLI_ROOT/lib/print 'comoto_cli bounce'
 
-print_and_eval_command $subcommand
+  if [[ $# -eq 0 ]]
+  then
+    # TODO Where is this dir variable defined? I think it can be replaced with $(comoto_cli cd monorepo)
+    # TODO make sure all into calls to the cli use `comoto_cli` longform. Add this note to a "contributions" README
+    subcommand="(comoto_cli cd monorepo && docker-compose down && docker-compose up -d) && comoto_cli logs"
+  elif [[ $# -gt 1 ]]
+  then
+    echo "error ... must have one or zero args" >&2
+    exit 1
+  elif container_name=$($COMOTO_CLI_ROOT/lib/container_name $1)
+  then
+    # TODO check for bad abbrev
+    # TODO this isn't working
+    subcommand="(comoto_cli cd monorepo docker restart $container_name) && comoto_cli logs $container_name"
+  else
+    echo "error ... $1 is a bad arg" >&2
+    exit 1
+  fi
 
-# TODO add the ability to bounce just a single webapp and/or the ability to bounce all three redline apps
+  print_and_eval_command $subcommand
+
+  # TODO add the ability to bounce just a single webapp and/or the ability to bounce all three redline apps
+}
+
+_comoto_cli_command_completion() {
+  local valid_args=$($COMOTO_CLI_ROOT/lib/container_name -l)
+  [[ $# -gt 1 ]] && return 1
+  COMPREPLY=( $(compgen -W "$valid_args" -- "$1") )
+}
diff --git a/comoto_cli/command/logs b/comoto_cli/command/logs
--- a/comoto_cli/command/logs
+++ b/comoto_cli/command/logs
@@ -1,18 +1,30 @@
 #!/bin/bash
 
-# defaults
-tail=10
+# TODO should this be a subcommand for container?
+#   It has the same completion as bounce too
 
-app_name="$($COMOTO_CLI_ROOT/lib/container_name $1)"
-base_subcommand="comoto_cli cd monorepo && docker-compose logs -f --tail=$tail"
+_comoto_cli_command_execute() {
 
-case $? in
-  0) subcommand=$base_subcommand ;;
-  # TODO Exit if that wasn't a proper abbreviation
-  1) subcommand="$base_subcommand $app_name" ;;
-  *) echo "TODO this is an epic fail!" >&2 && exit 1
-esac
+  # defaults
+  tail=10
 
-. $COMOTO_CLI_ROOT/lib/print
+  app_name="$($COMOTO_CLI_ROOT/lib/container_name $1)"
+  base_subcommand="comoto_cli cd monorepo && docker-compose logs -f --tail=$tail"
 
-print_and_eval_command "$subcommand"
+  case $? in
+    0) subcommand=$base_subcommand ;;
+    # TODO Exit if that wasn't a proper abbreviation
+    1) subcommand="$base_subcommand $app_name" ;;
+    *) echo "TODO this is an epic fail!" >&2 && exit 1
+  esac
+
+  . $COMOTO_CLI_ROOT/lib/print
+
+  print_and_eval_command "$subcommand"
+}
+
+_comoto_cli_command_completion() {
+  unset _comoto_cli_command_completion
+  . $COMOTO_CLI_ROOT/command/bounce
+  _comoto_cli_command_completion $*
+}
diff --git a/comoto_cli/command/repl b/comoto_cli/command/repl
--- a/comoto_cli/command/repl
+++ b/comoto_cli/command/repl
@@ -1,17 +1,25 @@
 #!/bin/bash
 
-# comoto_cli repl <container-abbreviation>
+# USAGE: comoto_cli repl <container-abbreviation>
 
-. $COMOTO_CLI_ROOT/lib/print
+_comoto_cli_command_execute() {
+  . $COMOTO_CLI_ROOT/lib/print
 
-# TODO add autocomplete
-# TODO error out when given an invalid $1
+  # TODO add autocomplete
+  # TODO error out when given an invalid $1
 
-case $1 in
-  # TODO is this correct or should this be in the "bash" command?
-  ecom) subcommand="ecom-bash" ;;
-  cg|jp|rz) subcommand="$1-iex" ;;
-  *) echo "TODO: this is an error" >&2 && exit 1
-esac
+  case $1 in
+    # TODO is this correct or should this be in the "bash" command?
+    ecom) subcommand="ecom-bash" ;;
+    cg|jp|rz) subcommand="$1-iex" ;;
+    *) echo "TODO: this is an error" >&2 && exit 1
+  esac
 
-print_and_eval_command --include-type "$subcommand"
+  print_and_eval_command --include-type "$subcommand"
+}
+
+_comoto_cli_command_completion() {
+  local valid_args="cg jp rz ecom"
+  [[ $# -gt 1 ]] && return 1
+  COMPREPLY=( $(compgen -W "$valid_args" -- "$1") )
+}
